#+TITLE:  GraphDuty: Graphite Monitoring and Alerting with PagerDuty
#+AUTHOR: Tim Dysinger <tim@dysinger.net>

* Introduction

  GraphDuty is a simple Haskell command line app to check Graphite and
  report any alertable conditions to PagerDuty.  It is compiled
  statically and you can build and distribute it like any other
  command line binary compiled for your servers.  [Alternatively it
  could be distributed via Git or Hackage.]

* Quickstart

*** [[Installing][Install]]

*** Edit [[Configuration][config]]

*** Run

    #+BEGIN_SRC sh
      graphduty -c /etc/my/path/to/config.json +RTS -N
    #+END_SRC

* Installing

*** Install [[http://hackage.haskell.org/platform][Haskell Platform]]

*** Update Cabal

    #+BEGIN_SRC sh
      cabal update
    #+END_SRC

*** Install GraphDuty

    #+BEGIN_SRC sh
      cd graphduty
      cabal install
    #+END_SRC

* Configuration

  The default config file is /etc/graphduty.json but you can also
  specify the filename at the command line.  You may use JSON or YAML
  for configuration.  Have a look at the example [[example.json][JSON]] or [[example.yaml][YAML]] file.

* Todo

*** TODO daemonizing - seems to exit right away and leave the pid file
*** TODO attoparsec parsing of string data so we are sure it's correct
